name: Docker Publish

on:
  push:
    tags:
      - 'v*'
      - '*'
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Lowercase repository owner
        id: repo-info
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ steps.repo-info.outputs.owner }}/mini-ca-frontend
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Lowercase repository owner
        id: repo-info
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Backend
        id: meta-backend
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ steps.repo-info.outputs.owner }}/mini-ca-backend
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push Backend
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Backend/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
